#!/usr/bin/env bash
# A bash script that changes the home IP address value

# The IP address to set for 'localhost'

ip_address="127.0.0.2"

# Create a temporary copy of the /etc/hosts file

sudo cp /etc/hosts /etc/hosts.bak



# Replace the line containing 'localhost' with the new IP address in the temporary copy

sudo sed -i "s/127.0.0.1.*/127.0.0.1 $ip_address localhost/" /etc/hosts.bak
echo "8.8.8.8 facebook.com" | sudo tee -a  /etc/hosts.bak


# Replace the original /etc/hosts file with the modified copy

sudo cp /etc/hosts.bak /etc/hosts



# Remove the temporary copy

sudo rm /etc/hosts.bak
